name: Codacy Analysis

on:
  workflow_call:
  workflow_run:
    workflows: 
      - Prettify
    types:
      - completed
    conclusions: 
      - success

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install
          cd src
          cd backendDev
          npm install
          cd ..
          cd frontendDev
          cd react
          npm install
          cd ..
          cd react-native
          npm install

      - name: Make analysis
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          token: ${{ secrets.CODACY_PROJECT_TOKEN }}

