name: Codacy Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Codacy reporter
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          token: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: Install dependencies
        run: |
          npm install
          cd backendDev
          cd  httpRequests
          cd HTTPRequests
          npm install
          cd .. 
          cd reactNativeHTTPRequests
          npm install

      - name: Install Codacy CLI
        run: |
          npm install -g codacy-analysis-cli

      - name: Run Codacy analysis
        run: |
          codacy-analysis-cli analyze --language JavaScript
