name: Codacy Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_run:
    workflows: 
      - Commits Checker
      - "Prettify"
      - "Linting check"
    types:
      - completed

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install
          cd backendDev
          cd httpRequests
          cd HTTPRequests
          npm install
          cd ..
          cd reactNativeHTTPRequests
          npm install

      - name: Make analysis
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          token: ${{ secrets.CODACY_PROJECT_TOKEN }}

