name: Commits Syntax Checker

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, review_requested, synchronize]
  push:
    branches:
      - "main"
  workflow_call:

jobs:
  check:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.0.3