name: Prettify

on:
  workflow_call:
  workflow_run:
    workflows: 
      - Commits Checker
    types:
      - completed
    conclusions: 
      - success

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Instalar dependencias (incluye Prettier)
    - name: Install dependencies
      run: |
          npm install
          cd src
          cd backendDev
          npm install
          cd ..
          cd frontendDev
          cd react
          npm install
          cd ..
          cd react-native
          npm install

    # Ejecutar Prettier y formatear los archivos si es necesario
    - name: Run Prettier and format files
      run: npx prettier --write '**/*.{js,jsx,ts,tsx,json,css,md}'

    # Verifica si hay cambios después de formatear
    - name: Check for changes
      run: |
        if [[ $(git status --porcelain) ]]; then
          echo "Changes detected, committing..."
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com" 
          git add .
          git commit -m "chore: format code with Prettier"
          git push
        else
          echo "No changes detected, everything is formatted correctly."
        fi
  
